### ISSUE TITLE
getorderinfo exception

### ISSUE THREAD

**Issue by alteralt** [Belyashik2K/AaioAsync#1]
![image](https://github.com/Belyashik2K/AaioAsync/assets/109542778/376ea255-3a0b-4916-8ac6-0a258b287421)

Version 
- AaioAsync - 0.1.7

**Comment by alteralt** [comment]
This error occurs on unpaid orders

To correct the ```Order``` model, you need to change the field ```commission_type```
```python
commission_type: typing.Optional[str] = None
```

**Comment by Belyashik2K** [comment]
Fixed in 0.1.8. Thank you for the information provided.
