### ISSUE TITLE
Pydantic error 

### ISSUE THREAD

**Issue by Whom-m0rty** [Belyashik2K/AaioAsync#2]
class OrderMethodInfo(BaseModel):
    min: OrderMethodCurrencies
    max: OrderMethodCurrencies
    commission_percent: float
    
замените commission_percent: float на commission_percent: str

**Comment by Whom-m0rty** [comment]
https://github.com/kewldan/AAIO/pull/8

Вот тут более подробно, лень делать пулл реквест.

**Comment by Belyashik2K** [comment]
Fixed in 0.1.10. Thanks.
